export const npcRoles = [
    "Blacksmith",
    "Innkeeper",
    "Merchant",
    "Town Guard",
    "Noble",
    "Bounty Hunter",
    "Alchemist",
    "Priest",
    "Scholar",
    "Sailor",
    "Bard",
    "Farmer",
    "Assassin",
    "Mercenary",
    "Mayor",
    "Librarian",
    "Gravekeeper",
    "Apothecary",
    "Hunter",
    "Stablemaster",
    "Cartographer",
    "Chandler (Candle Maker)",
    "Glassblower",
    "Fisherman",
    "Executioner",
    "Herbalist",
    "Banker",
    "Shipwright",
    "Scribe",
    "Arena Pit Fighter",
    "Street Performer",
    "Guild Master",
    "Spymaster",
    "Archivist",
    "Beggar",
    "Wainwright (Wagon Maker)",
    "Beekeeper",
    "Miner",
    "Tax Collector",
    "Artisan"
  ];
  