export const speechCharacteristics = [
  "a very slow manner",
  "a very quick pace",
  "a deep, booming voice",
  "a high-pitched voice",
  "a soft-spoken tone",
  "a gravelly voice",
  "a nasally tone",
  "a frequent stutter",
  "slurred words",
  "over-enunciated speech",
  "frequent pauses",
  "a monotone voice",
  "a sing-song tone",
  "mumbling often",
  "frequent whispers",
  "laughter between words",
  "constant throat clearing",
  "speech in rhymes",
  "excessively long, fancy words",
  "an overused catchphrase",
  "a rare tendency to speak at all",
  "heavy breathing while talking",
  "a noticeable lisp",
  "frequent voice cracks",
  "a perpetually sarcastic tone"
];
