export const visualTraits = [
  "heterochromia (different-colored eyes)",
  "a missing eye",
  "an unusually tall or short stature",
  "deep facial scars",
  "missing fingers",
  "a tattooed face or body",
  "a mechanical or wooden limb",
  "burn scars",
  "albino skin and hair",
  "glowing eyes",
  "a hood that they always wear",
  "elaborate jewelry or piercings",
  "wild, unkempt hair",
  "a bald head with strange markings",
  "extremely long fingernails",
  "fangs or unusually sharp teeth",
  "oddly elongated limbs",
  "animal-like features (whiskers, cat eyes, etc.)",
  "glowing runes on their skin",
  "gloves that they always wear",
  "a distinct birthmark in a noticeable place",
  "an unusual hair color (natural or dyed)",
  "a pale and sickly complexion",
  "a permanent smirk or scowl",
  "a mask that they always wear",
  "a hunched posture",
  "an extremely muscular build",
  "an unnaturally thin frame",
  "extra fingers or toes",
  "a constantly twitching eye",
  "freckles covering their face",
  "a hooked or crooked nose",
  "one ear noticeably larger than the other",
  "a long, braided beard",
  "perpetual dark circles under their eyes",
  "a tail (natural or grafted)",
  "a golden or metallic skin tone",
  "webbed fingers or toes",
  "one arm noticeably larger than the other",
  "a single long, sharp fingernail",
  "sharp, bird-like features",
  "a hunched back with protruding bones",
  "perpetually dirty or stained hands",
  "strikingly symmetrical features",
  "a deep, jagged scar across their neck",
  "a missing or split lip",
  "an extra joint in their fingers or toes",
  "bare feet, regardless of terrain",
  "one leg shorter than the other",
  "a strange, glowing symbol on their forehead"
];
